# Handling Missing Data

In [2]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [3]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [4]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data[0] = None

In [7]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

# Filtering Out Missing Data

In [8]:
from numpy import nan as NA

In [9]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [10]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])

In [13]:
cleaned = data.dropna()

In [14]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [16]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [21]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA

In [23]:
df

0         1         2
0 -0.135332       NaN       NaN
1 -0.532007       NaN       NaN
2 -0.767109       NaN -0.479699
3  0.734027       NaN -0.312522
4  1.111042 -0.349728  1.077051
5  0.010829  0.619064 -0.296418
6  0.059687  0.485997  0.007657

In [24]:
df.dropna()

0         1         2
4  1.111042 -0.349728  1.077051
5  0.010829  0.619064 -0.296418
6  0.059687  0.485997  0.007657

In [25]:
df.dropna(thresh=2)

0         1         2
2 -0.767109       NaN -0.479699
3  0.734027       NaN -0.312522
4  1.111042 -0.349728  1.077051
5  0.010829  0.619064 -0.296418
6  0.059687  0.485997  0.007657

# Filling In Missing Data

In [26]:
df.fillna(0)

0         1         2
0 -0.135332  0.000000  0.000000
1 -0.532007  0.000000  0.000000
2 -0.767109  0.000000 -0.479699
3  0.734027  0.000000 -0.312522
4  1.111042 -0.349728  1.077051
5  0.010829  0.619064 -0.296418
6  0.059687  0.485997  0.007657

In [28]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.135332  0.500000  0.000000
1 -0.532007  0.500000  0.000000
2 -0.767109  0.500000 -0.479699
3  0.734027  0.500000 -0.312522
4  1.111042 -0.349728  1.077051
5  0.010829  0.619064 -0.296418
6  0.059687  0.485997  0.007657

In [29]:
_=df.fillna(0, inplace=True)

In [30]:
df

0         1         2
0 -0.135332  0.000000  0.000000
1 -0.532007  0.000000  0.000000
2 -0.767109  0.000000 -0.479699
3  0.734027  0.000000 -0.312522
4  1.111042 -0.349728  1.077051
5  0.010829  0.619064 -0.296418
6  0.059687  0.485997  0.007657

In [32]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA

In [33]:
df

0         1         2
0 -0.707873  0.010844 -0.301927
1  1.551979  1.044607  0.706925
2 -1.145459       NaN -1.205189
3  1.201780       NaN -0.612069
4 -0.386794       NaN       NaN
5 -0.808679       NaN       NaN

In [34]:
df.fillna(method='ffill')

0         1         2
0 -0.707873  0.010844 -0.301927
1  1.551979  1.044607  0.706925
2 -1.145459  1.044607 -1.205189
3  1.201780  1.044607 -0.612069
4 -0.386794  1.044607 -0.612069
5 -0.808679  1.044607 -0.612069

In [35]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -0.707873  0.010844 -0.301927
1  1.551979  1.044607  0.706925
2 -1.145459  1.044607 -1.205189
3  1.201780  1.044607 -0.612069
4 -0.386794       NaN -0.612069
5 -0.808679       NaN -0.612069

In [36]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [37]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# Data Transformation

# Removing Duplicates

In [38]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})

In [39]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [41]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [42]:
data['v1'] = range(7)

In [43]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [44]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [45]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

# Transforming Data Using a Function or Mapping

In [46]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [47]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [48]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [49]:
lowercased = data['food'].str.lower()

In [50]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [51]:
data['animal'] = lowercased.map(meat_to_animal)

In [52]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [53]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

# Replacing Values

In [54]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [55]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [58]:
data.replace({-999:np.nan , -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

# Renaming Axis Indexes

In [59]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [60]:
transform = lambda x: x[:4].upper()

In [63]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [65]:
data.index = data.index.map(transform)

In [66]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [67]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [68]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [69]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [70]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

# Discretization and Binning 

In [71]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [72]:
bins = [18, 25, 35, 60, 100]

In [73]:
cats = pd.cut(ages, bins)

In [74]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [75]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [78]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [79]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [80]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [81]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [82]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [83]:
data = np.random.rand(20)

In [85]:
data

array([0.12334448, 0.41929948, 0.87553671, 0.04036267, 0.25464188,
       0.92298893, 0.17675159, 0.77633567, 0.85627466, 0.11843064,
       0.70281358, 0.56784155, 0.89571364, 0.78843532, 0.91370753,
       0.50456962, 0.9639845 , 0.45051618, 0.67181237, 0.18039296])

In [86]:
pd.cut(data, 4, precision=2)

[(0.039, 0.27], (0.27, 0.5], (0.73, 0.96], (0.039, 0.27], (0.039, 0.27], ..., (0.5, 0.73], (0.73, 0.96], (0.27, 0.5], (0.5, 0.73], (0.039, 0.27]]
Length: 20
Categories (4, interval[float64]): [(0.039, 0.27] < (0.27, 0.5] < (0.5, 0.73] < (0.73, 0.96]]

In [87]:
data = np.random.randn(1000)

In [88]:
cats = pd.qcut(data, 4)

In [89]:
cats

[(-0.00734, 0.635], (-0.00734, 0.635], (-3.768, -0.643], (-0.00734, 0.635], (-3.768, -0.643], ..., (-0.00734, 0.635], (-0.643, -0.00734], (-3.768, -0.643], (0.635, 3.858], (-0.00734, 0.635]]
Length: 1000
Categories (4, interval[float64]): [(-3.768, -0.643] < (-0.643, -0.00734] < (-0.00734, 0.635] < (0.635, 3.858]]

In [90]:
pd.value_counts(cats)

(0.635, 3.858]        250
(-0.00734, 0.635]     250
(-0.643, -0.00734]    250
(-3.768, -0.643]      250
dtype: int64

In [94]:
cats1 = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])
cats1

[(-0.00734, 1.213], (-0.00734, 1.213], (-1.345, -0.00734], (-0.00734, 1.213], (-3.768, -1.345], ..., (-0.00734, 1.213], (-1.345, -0.00734], (-1.345, -0.00734], (-0.00734, 1.213], (-0.00734, 1.213]]
Length: 1000
Categories (4, interval[float64]): [(-3.768, -1.345] < (-1.345, -0.00734] < (-0.00734, 1.213] < (1.213, 3.858]]

In [93]:
pd.value_counts(cats1)

(-0.00734, 1.213]     400
(-1.345, -0.00734]    400
(1.213, 3.858]        100
(-3.768, -1.345]      100
dtype: int64

# Detecting and Filtering Outliers

In [95]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [97]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.027275    -0.002335     0.012594     0.027502
std       0.995952     1.007878     1.011853     0.986287
min      -3.158513    -3.025340    -3.190331    -3.108740
25%      -0.717112    -0.693165    -0.669628    -0.620223
50%      -0.006657    -0.030885     0.016203    -0.006076
75%       0.687062     0.640462     0.671853     0.700888
max       2.781693     3.310012     3.726322     2.773241

In [98]:
col = data[2]

In [99]:
col[np.abs(col)>3]

72     3.726322
264    3.008322
364   -3.190331
465    3.451652
870   -3.048281
936    3.660480
Name: 2, dtype: float64

In [100]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
23  -3.060657  0.990854  0.286539 -0.951688
72   0.670896 -0.681666  3.726322  0.312084
95   0.494821  3.310012  0.086446  0.536141
261 -3.158513  0.325197  1.303371 -1.476761
264  2.035975  0.714629  3.008322  0.108976
364 -1.455236  0.151190 -3.190331 -0.764079
465  1.115188  1.856926  3.451652 -0.470593
516 -0.840421 -3.025340 -0.322020 -1.268024
870  0.080753 -0.739066 -3.048281 -0.866219
931 -0.135306  1.348176  0.064300 -3.108740
936  0.608197 -0.761363  3.660480  0.887880

In [101]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [102]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.027056    -0.002620     0.010986     0.027611
std       0.995283     1.006830     1.005063     0.985947
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.717112    -0.693165    -0.669628    -0.620223
50%      -0.006657    -0.030885     0.016203    -0.006076
75%       0.687062     0.640462     0.671853     0.700888
max       2.781693     3.000000     3.000000     2.773241

In [103]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0 -1.0
1 -1.0 -1.0 -1.0  1.0
2 -1.0  1.0  1.0 -1.0
3  1.0 -1.0 -1.0  1.0
4 -1.0 -1.0 -1.0 -1.0

In [104]:
data

0         1         2         3
0    0.119335  1.338198 -0.843835 -1.148536
1   -2.147051 -2.067328 -1.479918  1.010485
2   -0.301226  0.185875  1.284464 -1.703055
3    0.746072 -0.251961 -0.186038  0.746957
4   -0.719976 -1.166929 -0.468914 -0.341099
..        ...       ...       ...       ...
995  0.595422  0.444581  0.110062 -0.198688
996  0.664923 -0.306896  1.059826  0.100903
997  0.505674 -0.615214  1.732401 -0.796674
998  0.713511 -1.089881  0.831302  0.056609
999  0.925766  0.044541  0.515035  1.026104

[1000 rows x 4 columns]

# Permutation and Random Sampling

In [106]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [107]:
sampler = np.random.permutation(5)

In [108]:
sampler

array([3, 0, 2, 1, 4])

In [109]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [110]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11
1   4   5   6   7
4  16  17  18  19

In [112]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
4  16  17  18  19

In [113]:
choices = pd.Series([5, 7, -1, 6, 4])

In [114]:
draws = choices.sample(n=10, replace=True)

In [115]:
draws

3    6
0    5
2   -1
0    5
0    5
1    7
0    5
4    4
2   -1
0    5
dtype: int64

In [117]:
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

# Computing Indicator/Dummy Variables

In [118]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})

In [119]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [120]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [121]:
df_with_dummy = df[['data1']].join(dummies)

In [124]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [125]:
mnames = ['movie_id', 'title', 'genres']

In [129]:
movies = pd.read_table('Files/movielens/movies.dat', sep='::', header=None, names=mnames, engine='python')

In [130]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [133]:
all_genres=[]
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)

In [134]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [135]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [136]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [137]:
gen = movies.genres[0]

In [138]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [139]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [140]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [141]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [143]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [144]:
np.random.seed(12345)

In [145]:
values = np.random.rand(10)

In [147]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [148]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [149]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

# String Manipulation

# String Object Methods

In [150]:
val = 'a,b, guido'

In [151]:
val.split(',')

['a', 'b', ' guido']

In [152]:
pieces = [x.strip() for x in val.split(',')]

In [153]:
pieces

['a', 'b', 'guido']

In [154]:
first, second, third = pieces

In [155]:
first + '::' + second + '::' + third

'a::b::guido'

In [156]:
'::'.join(pieces)

'a::b::guido'

In [157]:
'guido' in val

True

In [158]:
val.index(',')

1

In [159]:
val.find(':')

-1

In [162]:
val.index(':')

ValueError: substring not found

In [163]:
val.count(',')

2

In [164]:
val.replace(',', '::')

'a::b:: guido'

In [165]:
val.replace(',', '')

'ab guido'

# Regular Expressions

In [166]:
import re

In [167]:
text = "foo bar\t baz \tqux"

In [169]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [170]:
regex = re.compile('\s+')

In [172]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [173]:
regex.findall(text)

[' ', '\t ', ' \t']

In [174]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
# re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [175]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [176]:
m = regex.search(text)

In [177]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [178]:
text[m.start():m.end()]

'dave@google.com'

In [179]:
print(regex.match(text))

None


In [180]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [181]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [182]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [183]:
m = regex.match('wesm@bright.net')

In [185]:
m.groups()

('wesm', 'bright', 'net')

In [186]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [187]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



# Vectorized String Functions in pandas

In [188]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [189]:
data = pd.Series(data)

In [190]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [191]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [192]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [194]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [195]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [202]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [203]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [206]:
data.str.get(1)

Dave       a
Steve      t
Rob        o
Wes      NaN
dtype: object

In [207]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object